ENV['COCOAPODS_DISABLE_STATS'] = 'true'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!


project 'Sample.xcodeproj'


target :Sample do
    pod 'InputMask', :path => '../../'
end
