source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!


xcodeproj 'Sample.xcodeproj'


target :Sample do
    pod 'InputMask', :path => '../../'
end
